# Generated by Django 3.2.12 on 2022-03-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airman',
            fields=[
                ('asma', models.BigIntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rank', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('hours', models.FloatField(blank=True, default=0, null=True)),
                ('airman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airman')),
            ],
        ),
        migrations.CreateModel(
            name='FlightHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('capthours', models.FloatField(blank=True, default=0, null=True)),
                ('cocapthours', models.FloatField(blank=True, default=0, null=True)),
                ('ifrhours', models.FloatField(blank=True, default=0, null=True)),
                ('nighthours', models.FloatField(blank=True, default=0, null=True)),
                ('nauthours', models.FloatField(blank=True, default=0, null=True)),
                ('crewhours', models.FloatField(blank=True, default=0, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('month', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('airman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airman')),
            ],
        ),
    ]
