# Generated by Django 3.2.12 on 2022-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220322_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='airman',
            name='geniko_synolo_oron',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='airman',
            name='katigoria_ptitikou',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airman',
            name='topothetisi',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
