# Generated by Django 3.2.12 on 2022-03-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220322_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airman',
            old_name='eidikotika',
            new_name='eidikotita',
        ),
    ]
