# Generated by Django 3.2.12 on 2022-03-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_eidikotika_airman_eidikotita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighthours',
            name='year',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
