# Generated by Django 3.2.12 on 2022-04-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_flighthours_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainhours',
            name='month',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainhours',
            name='year',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
