# Generated by Django 3.2.12 on 2022-04-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220403_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirmanTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptixio', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('diatagi_orismou', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('airman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airman')),
            ],
        ),
    ]
