# Generated by Django 3.2.12 on 2022-05-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_airmantrainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airman',
            name='katigoria_ptitikou',
        ),
        migrations.AddField(
            model_name='airman',
            name='katigoria_dikaioumeni',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='airman',
            name='katigoria_katoxiromeni',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
